"""
Blender Script Generator - Converts a VideoBlueprint into executable
Blender Python scripts that recreate the video's visual structure.

Generates:
- Scene setup (camera, lighting, world)
- Text overlays / title cards
- Motion graphics templates
- Keyframed animations matching the video's pacing
- Render settings matching source resolution/fps
"""

from pathlib import Path


class BlenderScriptGen:
    """Generate Blender Python scripts from a VideoBlueprint."""

    def generate(self, blueprint, output_dir: str = None) -> str:
        """Generate a complete Blender Python script."""
        bp = blueprint
        output_dir = Path(output_dir or ".")
        output_dir.mkdir(parents=True, exist_ok=True)

        script_path = output_dir / f"blender_project_{bp.title[:30].replace(' ', '_')}.py"

        # Parse resolution
        try:
            res_w, res_h = bp.resolution.split("x")
            res_w, res_h = int(res_w), int(res_h)
        except:
            res_w, res_h = 1920, 1080

        fps = int(bp.fps) if bp.fps else 30
        total_frames = int(bp.duration_seconds * fps)

        lines = [
            '"""',
            f'Auto-generated Blender script for: {bp.title}',
            f'Source: {bp.source_url}',
            f'Duration: {bp.duration_seconds}s | Resolution: {bp.resolution} | FPS: {fps}',
            f'Generated by Agent Team Video Creator',
            '"""',
            '',
            'import bpy',
            'import math',
            '',
            '# ═══════════════════════════════════════════════════════',
            '# CLEANUP',
            '# ═══════════════════════════════════════════════════════',
            'bpy.ops.object.select_all(action="SELECT")',
            'bpy.ops.object.delete(use_global=False)',
            '',
            'for collection in bpy.data.collections:',
            '    bpy.data.collections.remove(collection)',
            '',
            '# ═══════════════════════════════════════════════════════',
            '# RENDER SETTINGS',
            '# ═══════════════════════════════════════════════════════',
            'scene = bpy.context.scene',
            f'scene.render.resolution_x = {res_w}',
            f'scene.render.resolution_y = {res_h}',
            f'scene.render.fps = {fps}',
            f'scene.frame_start = 1',
            f'scene.frame_end = {total_frames}',
            'scene.render.image_settings.file_format = "FFMPEG"',
            'scene.render.ffmpeg.format = "MPEG4"',
            'scene.render.ffmpeg.codec = "H264"',
            'scene.render.ffmpeg.audio_codec = "AAC"',
            '',
            '# ═══════════════════════════════════════════════════════',
            '# WORLD / BACKGROUND',
            '# ═══════════════════════════════════════════════════════',
            'world = bpy.data.worlds.new("VideoWorld")',
            'scene.world = world',
            'world.use_nodes = True',
            'bg = world.node_tree.nodes["Background"]',
            'bg.inputs["Color"].default_value = (0.02, 0.02, 0.03, 1)  # Dark background',
            'bg.inputs["Strength"].default_value = 1.0',
            '',
            '# ═══════════════════════════════════════════════════════',
            '# CAMERA',
            '# ═══════════════════════════════════════════════════════',
            'bpy.ops.object.camera_add(location=(0, -8, 2), rotation=(math.radians(80), 0, 0))',
            'camera = bpy.context.active_object',
            'camera.name = "MainCamera"',
            'scene.camera = camera',
            'camera.data.lens = 50',
            '',
            '# ═══════════════════════════════════════════════════════',
            '# LIGHTING',
            '# ═══════════════════════════════════════════════════════',
            'bpy.ops.object.light_add(type="AREA", location=(3, -3, 5))',
            'key_light = bpy.context.active_object',
            'key_light.name = "KeyLight"',
            'key_light.data.energy = 500',
            'key_light.data.size = 4',
            '',
            'bpy.ops.object.light_add(type="AREA", location=(-3, -2, 3))',
            'fill_light = bpy.context.active_object',
            'fill_light.name = "FillLight"',
            'fill_light.data.energy = 200',
            'fill_light.data.size = 3',
            '',
        ]

        # Generate scene sections
        lines.append('# ═══════════════════════════════════════════════════════')
        lines.append(f'# SCENES ({len(bp.scenes)} detected)')
        lines.append('# ═══════════════════════════════════════════════════════')
        lines.append('')

        for i, scene_data in enumerate(bp.scenes):
            start_frame = int(scene_data.get("start", 0) * fps) + 1
            end_frame = int(scene_data.get("end", 0) * fps)
            desc = scene_data.get("description", f"Scene {i+1}")[:80]

            lines.append(f'# --- Scene {i+1}: {start_frame}f - {end_frame}f ---')
            lines.append(f'# Description: {desc}')
            lines.append('')

            # Create a text object for each scene (as title card / overlay)
            safe_desc = desc[:40].replace('"', '\\"').replace("'", "\\'")
            lines.append(f'bpy.ops.object.text_add(location=(0, 0, 0))')
            lines.append(f'text_obj = bpy.context.active_object')
            lines.append(f'text_obj.name = "Scene_{i+1}_Text"')
            lines.append(f'text_obj.data.body = "{safe_desc}"')
            lines.append(f'text_obj.data.align_x = "CENTER"')
            lines.append(f'text_obj.data.size = 0.3')
            lines.append(f'text_obj.location = (0, 0, {0.5 + i * 0.1})')
            lines.append('')

            # Keyframe visibility
            lines.append(f'# Keyframe visibility for scene {i+1}')
            lines.append(f'text_obj.hide_viewport = True')
            lines.append(f'text_obj.hide_render = True')
            lines.append(f'text_obj.keyframe_insert(data_path="hide_render", frame={max(1, start_frame - 1)})')
            lines.append(f'text_obj.hide_render = False')
            lines.append(f'text_obj.keyframe_insert(data_path="hide_render", frame={start_frame})')
            lines.append(f'text_obj.hide_render = True')
            lines.append(f'text_obj.keyframe_insert(data_path="hide_render", frame={end_frame})')
            lines.append('')

        # Transcript as markers
        if bp.transcript_segments:
            lines.append('# ═══════════════════════════════════════════════════════')
            lines.append('# TIMELINE MARKERS (from transcript)')
            lines.append('# ═══════════════════════════════════════════════════════')
            for j, seg in enumerate(bp.transcript_segments[:50]):
                frame = int(seg.get("start", 0) * fps) + 1
                text = seg.get("text", "")[:30].replace('"', "'")
                lines.append(f'scene.timeline_markers.new("{text}", frame={frame})')
            lines.append('')

        # Pacing notes as comments
        lines.append('# ═══════════════════════════════════════════════════════')
        lines.append('# PACING ANALYSIS')
        lines.append('# ═══════════════════════════════════════════════════════')
        for k, v in bp.pacing.items():
            lines.append(f'# {k}: {v}')
        lines.append('')

        lines.append(f'print("Blender project ready: {bp.title}")')
        lines.append(f'print("Total frames: {total_frames} | Scenes: {len(bp.scenes)}")')
        lines.append(f'print("Run render with: bpy.ops.render.render(animation=True)")')

        script_content = "\n".join(lines)
        script_path.write_text(script_content)

        return str(script_path)
