"""
Auto-generated Blender script for: Tokyo Twilight (東京暮色) - Yasujiro Ozu 1957
Source: https://www.youtube.com/watch?v=yZ3M8-d1QU4
Duration: 8460s | Resolution: 720x480 | FPS: 24
Generated by Agent Team Video Creator
"""

import bpy
import math

# ═══════════════════════════════════════════════════════
# CLEANUP
# ═══════════════════════════════════════════════════════
bpy.ops.object.select_all(action="SELECT")
bpy.ops.object.delete(use_global=False)

for collection in bpy.data.collections:
    bpy.data.collections.remove(collection)

# ═══════════════════════════════════════════════════════
# RENDER SETTINGS
# ═══════════════════════════════════════════════════════
scene = bpy.context.scene
scene.render.resolution_x = 720
scene.render.resolution_y = 480
scene.render.fps = 24
scene.frame_start = 1
scene.frame_end = 203040
scene.render.image_settings.file_format = "FFMPEG"
scene.render.ffmpeg.format = "MPEG4"
scene.render.ffmpeg.codec = "H264"
scene.render.ffmpeg.audio_codec = "AAC"

# ═══════════════════════════════════════════════════════
# WORLD / BACKGROUND
# ═══════════════════════════════════════════════════════
world = bpy.data.worlds.new("VideoWorld")
scene.world = world
world.use_nodes = True
bg = world.node_tree.nodes["Background"]
bg.inputs["Color"].default_value = (0.02, 0.02, 0.03, 1)  # Dark background
bg.inputs["Strength"].default_value = 1.0

# ═══════════════════════════════════════════════════════
# CAMERA
# ═══════════════════════════════════════════════════════
bpy.ops.object.camera_add(location=(0, -8, 2), rotation=(math.radians(80), 0, 0))
camera = bpy.context.active_object
camera.name = "MainCamera"
scene.camera = camera
camera.data.lens = 50

# ═══════════════════════════════════════════════════════
# LIGHTING
# ═══════════════════════════════════════════════════════
bpy.ops.object.light_add(type="AREA", location=(3, -3, 5))
key_light = bpy.context.active_object
key_light.name = "KeyLight"
key_light.data.energy = 500
key_light.data.size = 4

bpy.ops.object.light_add(type="AREA", location=(-3, -2, 3))
fill_light = bpy.context.active_object
fill_light.name = "FillLight"
fill_light.data.energy = 200
fill_light.data.size = 3

# ═══════════════════════════════════════════════════════
# SCENES (16 detected)
# ═══════════════════════════════════════════════════════

# --- Scene 1: 1f - 4320f ---
# Description: Opening credits and establishing shots - winter Tokyo streets, train stations, O

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_1_Text"
text_obj.data.body = "Opening credits and establishing shots -"
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 0.5)

# Keyframe visibility for scene 1
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=1)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=1)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=4320)

# --- Scene 2: 4321f - 11520f ---
# Description: Introduction of Shukichi (father/bank executive) at home. Establishing the famil

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_2_Text"
text_obj.data.body = "Introduction of Shukichi (father/bank ex"
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 0.6)

# Keyframe visibility for scene 2
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=4320)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=4321)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=11520)

# --- Scene 3: 11521f - 21600f ---
# Description: Akiko (younger sister) at college studying English shorthand. Scenes with classm

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_3_Text"
text_obj.data.body = "Akiko (younger sister) at college studyi"
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 0.7)

# Keyframe visibility for scene 3
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=11520)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=11521)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=21600)

# --- Scene 4: 21601f - 36000f ---
# Description: Takako (elder sister, Setsuko Hara) returns home from unhappy marriage with her 

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_4_Text"
text_obj.data.body = "Takako (elder sister, Setsuko Hara) retu"
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 0.8)

# Keyframe visibility for scene 4
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=21600)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=21601)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=36000)

# --- Scene 5: 36001f - 50400f ---
# Description: Night scenes in seedy bars and hangouts. Akiko meets Kenji. Shadow-laden express

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_5_Text"
text_obj.data.body = "Night scenes in seedy bars and hangouts."
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 0.9)

# Keyframe visibility for scene 5
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=36000)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=36001)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=50400)

# --- Scene 6: 50401f - 64800f ---
# Description: Family dinner scenes. Tension between sisters. Discussion of their mother who ab

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_6_Text"
text_obj.data.body = "Family dinner scenes. Tension between si"
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 1.0)

# Keyframe visibility for scene 6
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=50400)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=50401)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=64800)

# --- Scene 7: 64801f - 79200f ---
# Description: Akiko discovers she is pregnant. Internal turmoil. Scenes at college contrasted 

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_7_Text"
text_obj.data.body = "Akiko discovers she is pregnant. Interna"
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 1.1)

# Keyframe visibility for scene 7
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=64800)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=64801)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=79200)

# --- Scene 8: 79201f - 93600f ---
# Description: Akiko confronts Kenji about the pregnancy. He is evasive and cold. Bar scenes wi

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_8_Text"
text_obj.data.body = "Akiko confronts Kenji about the pregnanc"
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 1.2000000000000002)

# Keyframe visibility for scene 8
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=79200)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=79201)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=93600)

# --- Scene 9: 93601f - 108000f ---
# Description: The sisters learn of their mother Kisako's existence in Tokyo. Emotional turmoil

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_9_Text"
text_obj.data.body = "The sisters learn of their mother Kisako"
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 1.3)

# Keyframe visibility for scene 9
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=93600)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=93601)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=108000)

# --- Scene 10: 108001f - 122400f ---
# Description: Meeting with the absent mother Kisako. Confrontation scene. Complex emotions of 

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_10_Text"
text_obj.data.body = "Meeting with the absent mother Kisako. C"
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 1.4)

# Keyframe visibility for scene 10
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=108000)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=108001)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=122400)

# --- Scene 11: 122401f - 136800f ---
# Description: Takako grapples with her own marriage paralleling her mother's abandonment. Scen

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_11_Text"
text_obj.data.body = "Takako grapples with her own marriage pa"
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 1.5)

# Keyframe visibility for scene 11
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=122400)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=122401)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=136800)

# --- Scene 12: 136801f - 151200f ---
# Description: Akiko decides to get an abortion after realizing Kenji does not love her. Hospit

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_12_Text"
text_obj.data.body = "Akiko decides to get an abortion after r"
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 1.6)

# Keyframe visibility for scene 12
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=136800)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=136801)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=151200)

# --- Scene 13: 151201f - 165600f ---
# Description: Aftermath of abortion. Akiko's emotional state deteriorates. Father Shukichi beg

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_13_Text"
text_obj.data.body = "Aftermath of abortion. Akiko\'s emotional"
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 1.7000000000000002)

# Keyframe visibility for scene 13
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=151200)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=151201)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=165600)

# --- Scene 14: 165601f - 180000f ---
# Description: Takako makes decisions about her marriage. Parallel with her mother's past choic

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_14_Text"
text_obj.data.body = "Takako makes decisions about her marriag"
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 1.8)

# Keyframe visibility for scene 14
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=165600)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=165601)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=180000)

# --- Scene 15: 180001f - 194400f ---
# Description: Resolution scenes. Family confronts their shared pain. Ozu's restrained emotiona

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_15_Text"
text_obj.data.body = "Resolution scenes. Family confronts thei"
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 1.9000000000000001)

# Keyframe visibility for scene 15
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=180000)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=180001)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=194400)

# --- Scene 16: 194401f - 203040f ---
# Description: Final sequence. Empty streets at twilight. Ozu's pillow shots bookend the film. 

bpy.ops.object.text_add(location=(0, 0, 0))
text_obj = bpy.context.active_object
text_obj.name = "Scene_16_Text"
text_obj.data.body = "Final sequence. Empty streets at twiligh"
text_obj.data.align_x = "CENTER"
text_obj.data.size = 0.3
text_obj.location = (0, 0, 2.0)

# Keyframe visibility for scene 16
text_obj.hide_viewport = True
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=194400)
text_obj.hide_render = False
text_obj.keyframe_insert(data_path="hide_render", frame=194401)
text_obj.hide_render = True
text_obj.keyframe_insert(data_path="hide_render", frame=203040)

# ═══════════════════════════════════════════════════════
# TIMELINE MARKERS (from transcript)
# ═══════════════════════════════════════════════════════
scene.timeline_markers.new("[Opening credits - no dialogue", frame=1)
scene.timeline_markers.new("[Father Shukichi establishing ", frame=4321)
scene.timeline_markers.new("[Akiko at college - conversati", frame=11521)
scene.timeline_markers.new("[Takako returns home - discuss", frame=21601)
scene.timeline_markers.new("[Night bar scenes - Akiko and ", frame=36001)
scene.timeline_markers.new("[Family dinner - tension about", frame=50401)
scene.timeline_markers.new("[Akiko discovers pregnancy]", frame=64801)
scene.timeline_markers.new("[Confrontation with Kenji]", frame=79201)
scene.timeline_markers.new("[Discovery of mother Kisako]", frame=93601)
scene.timeline_markers.new("[Meeting with absent mother]", frame=108001)
scene.timeline_markers.new("[Takako's marriage parallels]", frame=122401)
scene.timeline_markers.new("[Akiko's abortion decision]", frame=136801)
scene.timeline_markers.new("[Aftermath and emotional fallo", frame=151201)
scene.timeline_markers.new("[Resolution and family reckoni", frame=165601)
scene.timeline_markers.new("[Final sequence - restrained e", frame=180001)
scene.timeline_markers.new("[Closing pillow shots and cred", frame=194401)

# ═══════════════════════════════════════════════════════
# PACING ANALYSIS
# ═══════════════════════════════════════════════════════
# pace: slow
# avg_scene_duration: 528.75
# total_scenes: 16
# shortest_scene: 180
# longest_scene: 600

print("Blender project ready: Tokyo Twilight (東京暮色) - Yasujiro Ozu 1957")
print("Total frames: 203040 | Scenes: 16")
print("Run render with: bpy.ops.render.render(animation=True)")